### ISSUE TITLE
hello, could you please tell me how to transform uml.ecore to typescript code?

### ISSUE THREAD

**Issue by burhanxz** [crossecore/ecore-typescript#1]

**Comment by schwichti** [comment]
Wow, you are starting with something big. 

CrossEcore is still in its early stages and publishing of CrossEcore's code generator is currently in progress.
However, I attached the code that was generated from [UML.ecore](http://git.eclipse.org/c/uml2/org.eclipse.uml2.git/tree/plugins/org.eclipse.uml2.uml/model/UML.ecore) so you can have a look how it would look like.
UML.ecore references Ecore.ecore and [Types.ecore](http://git.eclipse.org/c/uml2/org.eclipse.uml2.git/tree/plugins/org.eclipse.uml2.types/model/Types.ecore).
You need to add all packages as your dependencies (UML, Ecore, Types).
Every package should be located in its own directory.
Setting up the project can be a little tricky and depends on your project layout, if you are using module loaders (systemjs), etc.

[uml-typescript.zip](https://github.com/crossecore/ecore-typescript/files/2076377/uml-typescript.zip)

**Comment by burhanxz** [comment]
Thank you very much!

**Comment by schwichti** [comment]
You can generate the code using the code generator which is now available here: https://github.com/crossecore/crossecore-generator
