### ISSUE TITLE
Is there an export to XMI?

### ISSUE THREAD

**Issue by TheRittler** [crossecore/ecore-typescript#10]
Hey together, 

I am searching for an export of my model to XMI. Is there something I can use or write on my own with relatively low effort? I saw that there is an import from XMI, but I didn't find an export.

Thanks and Regards

**Comment by schwichti** [comment]
Currently, there is no XMI serialization. To implement a basic version is quite easy (when you are not using "exotic" Ecore features).

**Comment by schwichti** [comment]
Supported since 0.2.0. See https://github.com/crossecore/ecore-typescript/pull/28
