### ISSUE TITLE
Import declaration conflicts with local declaration 

### ISSUE THREAD

**Issue by checkcode555** [crossecore/ecore-typescript#14]
Hi,

I like the idea of the project. I was trying the code on my ecore model. However, I get an error. Some classes importing themselves, as for example:
 
import {EClass} from "./EClass";
... 
export interface EClass extends EClassifier

-> https://github.com/crossecore/ecore-typescript/blob/master/src/EClass.ts

Error: Import declaration conflicts with local declaration of 'EClass'

How do you go around this problem? Is there a secret setting to avoid this problem?

Thanks in advance!

**Comment by schwichti** [comment]
Sounds like the same problem described here: https://github.com/crossecore/crossecore-generator/issues/12

It is a bug in the code generator.
