### ISSUE TITLE
How to generate code?

### ISSUE THREAD

**Issue by magick93** [crossecore/ecore-typescript#5]
Hello

This project looks very interesting!

Can you tell me, how does one generate code from an ecore model?

And is it possible to add new code generators, for example, to generate a vuejs application?

Thanks

**Comment by schwichti** [comment]
Thank you for your interest in CrossEcore.

> Can you tell me, how does one generate code from an ecore model?

The code generator is a command line tool. I am working on making it public.

> is it possible to add new code generators, for example, to generate a vuejs application?

What are you going to do? I do not have experience with Vue.js, but I can tell you that CrossEcore-TypeScript play well along with Angular. You can see the Angular demos [EMFForms](https://github.com/crossecore/crossecore-emfforms/tree/master/angular-app) and [EclipseCon 2018](https://github.com/crossecore/examples-eclipsecon2018/tree/master/angular-app). 

Do you even need the features provided by CrossEcore or do you simply want to generate Vue.js components from an Ecore model, where, let's say there is a component for each EClass which has data attributes for each EAttribute and methods for each EOperation? If you do not need the features of CrossEcore, I recommend you to write an own code generator using [Xtend template expressions](https://www.eclipse.org/xtend/documentation/203_xtend_expressions.html#templates).

**Comment by magick93** [comment]
I was just using vuejs as an example. I'm very interested in MDE, especially using ecore models, and then using code generators. 

So each repository in the crossecore organisation here is essentially a plugin code generator that is invoked by a common cli?

**Comment by schwichti** [comment]
The repositories ecore-java, ecore-typescript, ecore-swift, and ecore-csharp are the Ecore/OCL runtime libraries for the respective programming languages. The Ecore runtime libraries are produced by running CrossEcore's code generator with Ecore.ecore as input. The code the generator would produce from your custom EPackage depends on these Ecore/OCL runtime libraries. So you always need to include the runtime libraries on your "classpath".

The TypeScript model code in the EMFForms and EclipseCon 2018 Demos is generated from custom Ecore models [view.ecore](https://github.com/crossecore/crossecore-emfforms/blob/master/model/view.ecore) or [Conference.ecore](https://github.com/crossecore/examples-eclipsecon2018/blob/master/model/model/Conference.ecore).

**Comment by schwichti** [comment]
If you do not need any of the features that the runtime libraries provide, i.e., persistence, factories, reflection, notifications, switches, referential integrity, validation, OCL, then it is much easier to write your own code generator.

**Comment by magick93** [comment]
Thanks, actually I do need many of these features.

Its really impressive work youve done!

Do you have an estimate on when the cli will be ready?

**Comment by schwichti** [comment]
> Do you have an estimate on when the cli will be ready?
Currently, I continue working on CrossEcore in my spare time and I do not have a concrete release date yet. You can email me and I send you the recent demo jar.

**Comment by schwichti** [comment]
The code generator is available here: https://github.com/crossecore/crossecore-generator
